all:
  vars:
    ansible_ssh_user: vagrant
    ansible_ssh_pass: vagrant
  hosts:
    k8s-master1:
      ansible_host: 10.10.1.3
      ip: 10.10.1.3
      access_ip: 10.10.1.3
    k8s-node1:
      ansible_host: 10.10.1.4
      ip: 10.10.1.4
      access_ip: 10.10.1.4
    k8s-node2:
      ansible_host: 10.10.1.5
      ip: 10.10.1.5
      access_ip: 10.10.1.5
  children:
    kube-master:
      hosts:
        k8s-master1:
    kube-node:
      hosts:
        k8s-node1:
        k8s-node2:
    etcd:
      hosts:
        k8s-master1:
        k8s-node1:
        k8s-node2:
    k8s-cluster:
      children:
        kube-master:
        kube-node:
    calico-rr:
      hosts: {}
