cluster = [
  { ip: "10.10.1.3", name: "k8s-master1" }, 
  { ip: "10.10.1.4", name: "k8s-node1"   }, 
  { ip: "10.10.1.5", name: "k8s-node2"   },
]

Vagrant.configure(2) do |config|
	config.vm.box = "centos/7"
	config.vm.box_url =  "http://mirrors.ustc.edu.cn/centos-cloud/centos/7/vagrant/x86_64/images/CentOS-7-x86_64-Vagrant-2002_01.VirtualBox.box"
	config.vm.box_download_checksum_type = "sha256"
	config.vm.box_download_checksum = "1e1127ac9dbb24cd61df71eae46d02db7580dbfa233fbba9c7316dfe29a530e0"
	config.vm.box_check_update = false
	config.ssh.insert_key = true  

	cluster.each do |server|
    	config.vm.define vm_name = server[:name] do |node|
    		node.vm.hostname = vm_name    
      		node.vm.network :private_network, ip: server[:ip]

    		node.vm.provider "virtualbox" do |vb|
    			vb.cpus = 2 if ! server[:vcpu]
        		vb.memory = 2048 if ! server[:ram]
    			vb.gui = false
    		end

    		node.vm.provision "shell", :privileged => true, inline: <<-SSHD
    			sed -i "/PasswordAuthentication/d" /etc/ssh/sshd_config
    			echo "PasswordAuthentication yes" >> /etc/ssh/sshd_config
    			echo "PermitRootLogin no" >> /etc/ssh/sshd_config
    			systemctl restart sshd
    		SSHD
    		
    		node.vm.provision "shell", :privileged => true, inline: <<-INIT
    			swapoff -a
    			systemctl stop firewalld
    			systemctl disable firewalld
    		INIT
    	end
	end
end